### ISSUE TITLE
Can't edit form cell items

### ISSUE THREAD

**Issue by AntonUdalow** [XRM-OSS/Xrm-Quick-Edit#35]
Hi, thank you very much for your work, it's amazing! But I can't edit form cell items on locked entity, It works for tabs and sections translation, but not on the cell level under section - I don't get edit mode on double click there. I have tried with 3.10.0 and 3.14.1, both as unmanaged solution under CRM 9.1 online. But it works for me on premise with 3.3.1 managed solution (this version is working for me without entity lock requirement, but has already translation locks entity?) under CRM 8.2.

**Comment by AntonUdalow** [comment]
I have found the enableLocking (entity lock) and lockFormCells properties in config, but why are you locking cells as default setting now, are there any problems with that?

**Comment by lar-mar** [comment]
Labels for attributes are ideally only changed on attribute level.
When you change the label for the attribute on form level the user will be most probably confused because he will experience different labels in the form and in views or advanced find foor the same attribute.
Therefore this lock was introduced so that attribute labels on form level are not touched by mistake.

**Comment by DigitalFlow** [comment]
Thanks for explaining it @lar-mar.
Any questions left @AntonUdalow?

Kind Regards,
Florian
