### ISSUE TITLE
Error: Not Found: The given solution unique name (Translations) is not valid

### ISSUE THREAD

**Issue by fuattatar** [XRM-OSS/Xrm-Quick-Edit#36]
When i click save it throws that error "Error: Not Found: The given solution unique name (Translations) is not valid".

Browser:Chrome Version 85.0.4183.102 (Official Build) (64-bit)

Crm Version:  (DB 9.0.15.9) on-premises

Picture:

![translate error](https://user-images.githubusercontent.com/2419809/92700960-18627a00-f358-11ea-825c-d20d3a1dfbb7.png)

**Comment by lar-mar** [comment]
The solution contains a config file oss_/XrmQuickEdit/config/XrmQuickEditConfig.js
Here is a solution defined which is used to add all components translated in the dashboard.
![image](https://user-images.githubusercontent.com/15412588/93479546-bb893580-f8fc-11ea-8428-46ded2cc9af7.png)
This solution needs to exist otherwise the logic cannot add the components to this solution.

**Comment by DigitalFlow** [comment]
Hi everyone,

@lar-mar: Thanks for catching up 👍 
@fuattatar: I hope the fix described by @lar-mar helped you. In release v3.14.2 this default value is removed, should not be an issue on this version anymore.

I'll close this for now, please reopen if issues persist.

Kind Regards,
Florian
